server:
  port: 8082
spring:
  application:
    name: service-product
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/testmy?useUnicode=true&characterEncoding=utf8
    username: root
    password: root
  jpa:
    database: MySQL
    show-sql: true
    open-in-view: true
eureka:
  client:
    service-url:
     defaultZone: http://127.0.0.1:8080/eureka/
name: ddddddddddddddddddddddddddddddddddddddddddddddd
